export const HARDWARE_DEPTH = 0.27;
const HARDWARE_BACK_Z = -0.31;
export const HARDWARE_CENTER_Z = HARDWARE_BACK_Z + HARDWARE_DEPTH / 2;
const HARDWARE_GAP = 0.04;

export const SERVER_WIDTH = 0.16;
export const SERVER_HEIGHT = 0.16;
export const SERVER_FOOT_HEIGHT = 0.006;
export const SERVER_BODY_HEIGHT = SERVER_HEIGHT - SERVER_FOOT_HEIGHT;
export const SERVER_BODY_CENTER_Y = SERVER_FOOT_HEIGHT + SERVER_BODY_HEIGHT / 2;
export const MAC_STUDIO_WIDTH = 0.27;
export const MAC_STUDIO_HEIGHT = 0.13;
export const HUB_WIDTH = 0.13;
export const HUB_HEIGHT = 0.034;
export const HUB_DEPTH = 0.23;

const CLUSTER_WIDTH = SERVER_WIDTH + MAC_STUDIO_WIDTH + HUB_WIDTH + HARDWARE_GAP * 2;
const CLUSTER_LEFT = -CLUSTER_WIDTH / 2;

export const SERVER_X = CLUSTER_LEFT + SERVER_WIDTH / 2;
export const MAC_STUDIO_X = CLUSTER_LEFT + SERVER_WIDTH + HARDWARE_GAP + MAC_STUDIO_WIDTH / 2;
export const HUB_X = CLUSTER_LEFT + CLUSTER_WIDTH - HUB_WIDTH / 2;
